### ISSUE TITLE
get_inchi_key() returning None for some compounds

### ISSUE THREAD

**Issue by pvtodorov** [libChEBI/libChEBIpy#10]
The following query returns None, yet [CHEBI:4700](https://www.ebi.ac.uk/chebi/searchId.do;jsessionid=297672D6CDE29003B1A0772B960C7CC6?chebiId=CHEBI:4700) has an InChI key (YSNPSKZBOQYUHH-AFUNOPLTSA-N) on the ChEBI site
`libchebipy.ChebiEntity('4700').get_inchi_key()`

**Comment by neilswainston** [comment]
Unable to reproduce in either Python 2 or 3.

**Comment by lisavader** [comment]
I have the same issue in python 3.10, I get None for the above example (and other compounds that clearly have an InChIKey available).
