### ISSUE TITLE
Several tests failed

### ISSUE THREAD

**Issue by fabienjourdan** [libChEBI/libChEBIpy#13]
Dear authors,
Thanks for your library.
We were using (with great pleasure !) your library but we are now facing issues. For example we don't get any results with the outgoing and incoming options.
We did clone the code, launched the tests and recieved the following results:
FAILED (failures=15, errors=20)
Could you let us know if there is an alternative option, for instance to access incomings and outgoings of ChEBIs.
Many thanks in advance

**Comment by neilswainston** [comment]
Hi Fabien,

Sorry about that. The ChEBI people altered their formats. They fixed the Java version but left the Python to me!

Try the latest version - should be ok.

Cheers,

Neil.

**Comment by muthuvenkat** [comment]
Sorry @neilswainston, I was about to work with python, we use java version for validation, that's why it got fixed first.

**Comment by neilswainston** [comment]
No problem at all! Thanks for the updates!

Neil Swainston, PhD

Institute of Integrative Biology
University of Liverpool
Liverpool L69 7ZB
United KIngdom



On 9 Oct 2019, at 14:02, Venkatesh Muthukrishnan <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry @neilswainston<https://github.com/neilswainston>, I was about to work with python, we use java version for validation, that's why it got fixed first.

**Comment by fabienjourdan** [comment]
Thanks Neil for the quick feedback.
I did try to do the pip install again, but sounds I still face the same issue.
Maybe I did something wrong?
Thanks again and sorry for all the questions, I am not a native python speaker.
Fabien

**Comment by neilswainston** [comment]
Sorry, Fabien, that’s entirely my fault. I forgot to update the PyPI repository.

Please try the pip upgrade again now.

Neil Swainston, PhD

Institute of Integrative Biology
University of Liverpool
Liverpool L69 7ZB
United KIngdom



On 11 Oct 2019, at 15:07, fabienjourdan <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Neil for the quick feedback.
I did try to do the pip install again, but sounds I still face the same issue.
Maybe I did something wrong?
Thanks again and sorry for all the questions, I am not a native python speaker.
Fabien

**Comment by fabienjourdan** [comment]
Works fine now!!
Thanks for the very quick feedback!!
