### ISSUE TITLE
Custom download path

### ISSUE THREAD

**Issue by vsoch** [libChEBI/libChEBIpy#15]
hey maintainers! I'm looking at the hard coded download path https://github.com/libChEBI/libChEBIpy/blob/master/libchebipy/_parsers.py#L55 and wondering if there is any room for being able to customize this? The easiest thing to do would be to look for an envar (e.g., `LIBCHEBI_DOWNLOAD_PATH`) and then default to user home if it's not found. I'm working on a project where ideally I don't want this to be saved in the user's home, so I'm hoping this is something we could do! If you'd like to talk about the implementation, I'd be happy to do it and open a PR. Thank you!

**Comment by vsoch** [comment]
Quick update - I did find how to customize this. I'm wondering if you have had any users that customize / use a custom storage backend, such as cloud storage? We won't be having write to the filesystem. It would be great if you would want to discuss this, and then I'll do whatever work is needed (customization in our code or even a PR here) to make that possible.

**Comment by neilswainston** [comment]
Hi there,

Yep, sure. Just fork away and ping me the PR once you’re done.

Best wishes,

Neil.

On 17 Jul 2020, at 17:00, Vanessasaurus <notifications@github.com<mailto:notifications@github.com>> wrote:



hey maintainers! I'm looking at the hard coded download path https://github.com/libChEBI/libChEBIpy/blob/master/libchebipy/_parsers.py#L55 and wondering if there is any room for being able to customize this? The easiest thing to do would be to look for an envar (e.g., LIBCHEBI_DOWNLOAD_PATH) and then default to user home if it's not found. I'm working on a project where ideally I don't want this to be saved in the user's home, so I'm hoping this is something we could do! If you'd like to talk about the implementation, I'd be happy to do it and open a PR. Thank you!

**Comment by vsoch** [comment]
Closed with #16
