### ISSUE TITLE
.get_references() utf-8 error

### ISSUE THREAD

**Issue by pvtodorov** [libChEBI/libChEBIpy#9]
Hi,

Running on 

- Mac OS Sierra 10.12.1
- '3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12) \n[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]'

When I execute the following block of code:
```
import libchebipy
a = libchebipy.ChebiEntity('4700')
a.get_references()
```

I get the following error
```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-20-2852e42086f9> in <module>()
----> 1 a.get_references()

/Users/petar/anaconda/envs/py35/lib/python3.5/site-packages/libchebipy/_chebi_entity.py in get_references(self)
    236     def get_references(self):
    237         '''Returns references'''
--> 238         return parsers.get_references(self.__get_all_ids())
    239 
    240     def get_compound_origins(self):

/Users/petar/anaconda/envs/py35/lib/python3.5/site-packages/libchebipy/_parsers.py in get_references(chebi_ids)
    430         next(textfile)
    431 
--> 432         for line in textfile:
    433             tokens = line.strip().split('\t')
    434 

/Users/petar/anaconda/envs/py35/lib/python3.5/codecs.py in decode(self, input, final)
    319         # decode input (taking the buffer into account)
    320         data = self.buffer + input
--> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
    322         # keep undecoded input until the next call
    323         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 4618: invalid start byte
```

**Comment by pvtodorov** [comment]
I should also mention that when I [pull this file via FTP](ftp://ftp.ebi.ac.uk/pub/databases/chebi/Flat_file_tab_delimited/reference.tsv.gz) from their site, unzip it, and try to open it using pandas.read_table I get the same `UnicodeDecodeError`. I can, however read this when I tell pandas that the encoding is `'iso-8859-1'`

It seems to be a Unicode error that is caused by the data.

**Comment by neilswainston** [comment]
Hi there,

Sorry to hear you're having problems. I've tried recreating your issue with the *latest* version of libChEBI, and have been unable to reproduce it...

import libchebipy
a = libchebipy.ChebiEntity('4700')
refs = a.get_references()
print len(refs)
1
print refs
[{'_Reference__reference_id': '223439569', '_Reference__reference_db_name': 'PubChem', '_Reference__location_in_ref': None, '_Reference__reference_name': None}]

Please let me know if this is still an issue!

Best wishes,

Neil.

**Comment by pvtodorov** [comment]
Hi Neil,

Thanks for the response. It appears to be a Python2/3 incompatibility. Running on Python2 fixes the issue. It is also resolved when loading the references.tsv in pandas under Python2.

Petar

**Comment by neilswainston** [comment]
Fix added, and added to unit tests.
